# Generated by Django 3.2.7 on 2021-11-20 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_source', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='mess',
        ),
        migrations.AddField(
            model_name='member',
            name='mess',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_source.mess'),
        ),
    ]
