# Generated by Django 3.2.7 on 2021-11-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_source', '0007_cashdeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='amountspend',
            name='person_spend',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
