# Generated by Django 3.2.7 on 2021-11-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_source', '0009_alter_amountspend_person_spend'),
    ]

    operations = [
        migrations.AddField(
            model_name='amountspend',
            name='spend_total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
