# Generated by Django 3.2.7 on 2021-11-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_source', '0010_amountspend_spend_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdeposit',
            name='balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
