# Generated by Django 3.2.7 on 2021-11-22 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_source', '0012_alter_bills_mess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountspend',
            name='mess',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_source.mess'),
        ),
        migrations.AlterField(
            model_name='cashdeposit',
            name='mess',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_source.mess'),
        ),
        migrations.AlterField(
            model_name='member',
            name='mess',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_source.mess'),
        ),
    ]
